// Mocks generated by Mockito 5.1.0 from annotations
// in banki_flutter/test/features/shop/data/repositories/shop_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:banki_flutter/core/platform/network_service.dart' as _i6;
import 'package:banki_flutter/features/shop/data/datasources/local/shop_local_datasource.dart'
    as _i3;
import 'package:banki_flutter/features/shop/data/datasources/remote/shop_remote_datasource.dart'
    as _i2;
import 'package:banki_flutter/features/shop/data/models/product_response_model.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [ShopRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockShopRemoteDataSource extends _i1.Mock
    implements _i2.ShopRemoteDataSource {
  MockShopRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [ShopLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockShopLocalDataSource extends _i1.Mock
    implements _i3.ShopLocalDataSource {
  MockShopLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void>? cacheAllProducts(_i5.ProductResponseModel? model) =>
      (super.noSuchMethod(Invocation.method(#cacheAllProducts, [model]),
              returnValueForMissingStub: Future<void>.value())
          as _i4.Future<void>?);
}

/// A class which mocks [NetworkService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkService extends _i1.Mock implements _i6.NetworkService {
  MockNetworkService() {
    _i1.throwOnMissingStub(this);
  }
}
